"""Career Pages search — direct fan-out across companies' OWN career sites.

Covers the non-Workday universe: companies hosting jobs on Greenhouse,
Lever, Ashby, SmartRecruiters, Workable, Recruitee (public JSON job-board
APIs — no scraping, no credits) plus custom enterprise platforms (Amazon,
Microsoft) with public search APIs. The validated catalog lives in
career_pages_catalog.py (generated by scripts/validate_career_tenants.py).

Board-style ATSes return the WHOLE open-roles list in one or two requests,
so the fan-out is one task per company (vs Workday's tenants x terms) and
descriptions mostly arrive inline — real skill scores from the first pass.

Scoring, tailor-feasibility, seniority and sponsorship semantics are shared
with the Workday tab (imported from workday_jobs_service) so both tabs rank
identically against the user's resume.
"""
from __future__ import annotations

import hashlib
import json
import logging
import re
import time
from concurrent.futures import ThreadPoolExecutor, TimeoutError, as_completed
from datetime import datetime, timezone
from typing import Any, Callable, Dict, List, Optional, Tuple

import requests

from services.career_pages_catalog import ATS_KINDS, CAREER_PAGES_CATALOG, INDUSTRIES
from services.workday_jobs_service import (
    GLOBAL_KEEP,
    WINDOW_DAYS,
    _attach_feasibility,
    _attach_sponsorship,
    _build_match_regex,
    _days_ago,
    _derive_query_terms,
    _derive_skill_terms,
    _geo_keep_us,
    _html_to_text,
    _load_resume_profile,
    _role_matchers,
    _score_jobs,
    _US_STATE_RE,
)

logger = logging.getLogger(__name__)

REQUEST_TIMEOUT = 8
DETAIL_TIMEOUT = 6
OVERALL_TIMEOUT = 480
MAX_WORKERS = 64
PER_COMPANY_KEEP = 30
DETAIL_ENRICH_TOP = 250      # rows still lacking a description after fetch
DETAIL_ENRICH_RECENT = 300
STREAM_EVERY_TASKS = 25
STREAM_TOP = 120
MAX_QUERY_TERMS = 4
TOTAL_TERMS_CAP = 6
RESULT_SCHEMA_VERSION = 1

CACHE_COLLECTION = "career_pages_cache"
CACHE_TTL_SECONDS = 6 * 3600
CACHE_FRESH_SECONDS = 3 * 3600

_HEADERS = {
    "User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                   "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36"),
    "Accept": "application/json",
}

_SESSION = requests.Session()
_SESSION.headers.update(_HEADERS)
try:
    from requests.adapters import HTTPAdapter
    _adapter = HTTPAdapter(pool_connections=32, pool_maxsize=8, max_retries=0)
    _SESSION.mount("https://", _adapter)
except Exception:  # pragma: no cover
    pass


def _drain_pools() -> None:
    """Release pooled sockets — Lambda FD budget is 1024 (see Errno 24)."""
    try:
        for adapter in _SESSION.adapters.values():
            if hasattr(adapter, "poolmanager"):
                adapter.poolmanager.clear()
    except Exception:
        pass


# ----------------------------------------------------------------------
# Normalization helpers
# ----------------------------------------------------------------------

def _iso(dt_str: Optional[str]) -> str:
    return str(dt_str or "")


def _ms_to_iso(ms: Any) -> str:
    try:
        return datetime.fromtimestamp(int(ms) / 1000, tz=timezone.utc).isoformat()
    except (TypeError, ValueError, OSError):
        return ""


def _posted_text(days: Optional[int]) -> str:
    if days is None:
        return ""
    if days == 0:
        return "Posted Today"
    if days == 1:
        return "Posted Yesterday"
    return f"Posted {days} Days Ago"


_REMOTE_RE = re.compile(r"\bremote\b", re.IGNORECASE)

# Display names for the JobCard's source badge (Workday rows say "Workday").
_ATS_LABEL = {
    "greenhouse": "Greenhouse", "lever": "Lever", "ashby": "Ashby",
    "smartrecruiters": "SmartRecruiters", "workable": "Workable",
    "recruitee": "Recruitee",
}

# Explicit non-US markers for ATS location strings (board APIs often give
# "City, Country" or ISO codes). US rows: US country codes, US state
# suffixes, or "Remote - US". Anything explicitly foreign is dropped when
# us_only; ambiguous rows fall through to _geo_keep_us's tiering.
_COUNTRY_OK = {"us", "usa", "united states", "united states of america"}


def _row(company: Dict[str, str], raw_id: Any, title: str, url: str,
         date_posted: str, location: str, description: str = "",
         is_remote: Optional[bool] = None, country: str = "") -> Dict[str, Any]:
    days = _days_ago(date_posted) if date_posted else None
    return {
        "job_id": f"{company['ats']}:{company['slug']}:{raw_id}",
        "title": str(title or "").strip()[:200],
        "company": company["display_name"],
        "tenant": company["slug"],
        "ats": company["ats"],
        "industry": company.get("industry") or "other",
        "location": str(location or "").strip()[:160],
        "country_hint": str(country or "").strip().lower(),
        "date_posted": date_posted,
        "days_ago": days,
        "posted_text": _posted_text(days),
        "apply_link": url,
        "description": description[:5000] if description else "",
        "is_remote": bool(is_remote) if is_remote is not None
                     else bool(_REMOTE_RE.search(location or "")),
        "source": _ATS_LABEL.get(company["ats"], company["ats"]),
    }


# ----------------------------------------------------------------------
# Per-ATS board fetchers — one call returns the company's open roles
# ----------------------------------------------------------------------

def _fetch_greenhouse(c: Dict[str, str]) -> List[Dict[str, Any]]:
    r = _SESSION.get(
        f"https://boards-api.greenhouse.io/v1/boards/{c['slug']}/jobs?content=false",
        timeout=REQUEST_TIMEOUT)
    r.raise_for_status()
    out = []
    for j in (r.json() or {}).get("jobs") or []:
        date = j.get("first_published") or j.get("updated_at") or ""
        out.append(_row(
            c, j.get("id"), j.get("title") or "", j.get("absolute_url") or "",
            _iso(date), ((j.get("location") or {}).get("name")) or ""))
    return out


def _fetch_lever(c: Dict[str, str]) -> List[Dict[str, Any]]:
    r = _SESSION.get(
        f"https://api.lever.co/v0/postings/{c['slug']}?mode=json",
        timeout=REQUEST_TIMEOUT)
    r.raise_for_status()
    data = r.json()
    out = []
    for j in data if isinstance(data, list) else []:
        cats = j.get("categories") or {}
        wp = str(j.get("workplaceType") or "").lower()
        out.append(_row(
            c, j.get("id"), j.get("text") or "", j.get("hostedUrl") or "",
            _ms_to_iso(j.get("createdAt")), cats.get("location") or "",
            description=str(j.get("descriptionPlain") or "")[:5000],
            is_remote=(wp == "remote") or None,
            country=str(j.get("country") or "")))
    return out


def _fetch_ashby(c: Dict[str, str]) -> List[Dict[str, Any]]:
    # Ashby's posting API is GET-only (POST returns 401).
    r = _SESSION.get(
        f"https://api.ashbyhq.com/posting-api/job-board/{c['slug']}",
        timeout=REQUEST_TIMEOUT)
    r.raise_for_status()
    out = []
    for j in (r.json() or {}).get("jobs") or []:
        if j.get("isListed") is False:
            continue
        loc = j.get("location") or ""
        secondary = ", ".join(
            (s.get("location") or "") for s in j.get("secondaryLocations") or [])
        address = (((j.get("address") or {}).get("postalAddress") or {})
                   .get("addressCountry") or "")
        out.append(_row(
            c, j.get("id"), j.get("title") or "",
            j.get("jobUrl") or j.get("applyUrl") or "",
            _iso(j.get("publishedAt")),
            loc + ((" · " + secondary) if secondary else ""),
            description=_html_to_text(j.get("descriptionHtml") or "")[:5000],
            is_remote=j.get("isRemote"),
            country=address))
    return out


def _fetch_smartrecruiters(c: Dict[str, str]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    offset = 0
    for _page in range(2):  # 100/page; 200 newest is plenty for a 30d window
        # country=us server-side: giant multinationals (AccorHotels: 5,800+
        # postings) would otherwise bury the US slice beyond our 2 pages.
        r = _SESSION.get(
            f"https://api.smartrecruiters.com/v1/companies/{c['slug']}/postings"
            f"?limit=100&offset={offset}&country=us", timeout=REQUEST_TIMEOUT)
        r.raise_for_status()
        data = r.json() or {}
        content = data.get("content") or []
        for j in content:
            loc = j.get("location") or {}
            city = ", ".join(x for x in [loc.get("city"), loc.get("region")] if x)
            out.append(_row(
                c, j.get("id"), j.get("name") or "",
                f"https://jobs.smartrecruiters.com/{c['slug']}/{j.get('id')}",
                _iso(j.get("releasedDate")), city,
                is_remote=bool(loc.get("remote")) or None,
                country=str(loc.get("country") or "")))
        offset += len(content)
        if len(content) < 100:
            break
    return out


def _fetch_workable(c: Dict[str, str]) -> List[Dict[str, Any]]:
    r = _SESSION.get(
        f"https://apply.workable.com/api/v1/widget/accounts/{c['slug']}",
        timeout=REQUEST_TIMEOUT)
    r.raise_for_status()
    out = []
    for j in (r.json() or {}).get("jobs") or []:
        loc = ", ".join(x for x in [j.get("city"), j.get("state")] if x)
        out.append(_row(
            c, j.get("shortcode") or j.get("code"), j.get("title") or "",
            j.get("url") or "", _iso(j.get("published_on")), loc,
            is_remote=bool(j.get("telecommuting")) or None,
            country=str(j.get("country") or "")))
    return out


def _fetch_recruitee(c: Dict[str, str]) -> List[Dict[str, Any]]:
    r = _SESSION.get(f"https://{c['slug']}.recruitee.com/api/offers/",
                     timeout=REQUEST_TIMEOUT)
    r.raise_for_status()
    out = []
    for j in (r.json() or {}).get("offers") or []:
        out.append(_row(
            c, j.get("id"), j.get("title") or "", j.get("careers_url") or "",
            _iso(j.get("created_at")), j.get("location") or "",
            description=_html_to_text(j.get("description") or "")[:5000],
            is_remote=(str(j.get("remote")).lower() == "true") or None,
            country=str(j.get("country_code") or "")))
    return out


FETCHERS: Dict[str, Callable[[Dict[str, str]], List[Dict[str, Any]]]] = {
    "greenhouse": _fetch_greenhouse,
    "lever": _fetch_lever,
    "ashby": _fetch_ashby,
    "smartrecruiters": _fetch_smartrecruiters,
    "workable": _fetch_workable,
    "recruitee": _fetch_recruitee,
}


# ----------------------------------------------------------------------
# US filter for board rows
# ----------------------------------------------------------------------

# Board ATSes often print BARE foreign hub cities ("Dublin", "London") with
# no country — the Workday tiering keeps those because "Dublin, CA" is also
# a US city. Only applied when the string carries no US signal at all.
_FOREIGN_CITY_RE = re.compile(
    r"\b(dublin|london|toronto|vancouver|montreal|ottawa|waterloo|singapore|"
    r"bangalore|bengaluru|hyderabad|chennai|pune|mumbai|delhi|noida|gurgaon|"
    r"amsterdam|berlin|munich|paris|warsaw|krakow|tokyo|osaka|sydney|"
    r"melbourne|tel aviv|sao paulo|mexico city|lisbon|madrid|barcelona|"
    r"zurich|stockholm|copenhagen|oslo|helsinki|prague|bucharest|tallinn|"
    r"athens|milan|rome|brussels|vienna|belgrade|zagreb|seoul|taipei|"
    r"shanghai|beijing|hong kong|manila|jakarta|kuala lumpur|hanoi|cairo|"
    r"lagos|nairobi|cape town|johannesburg|buenos aires|santiago|bogota|lima)\b",
    re.IGNORECASE)
_US_WORD_RE = re.compile(r"united states|\busa\b|\bu\.s\.\b|remote[ -]+us\b",
                         re.IGNORECASE)
# An explicit foreign COUNTRY overrides everything — board strings like
# "Canada - Remote (ON, AB, or NS Only)" would otherwise be rescued by the
# US-state tier (the English word "or" collides with Oregon's code).
_FOREIGN_COUNTRY_RE = re.compile(
    r"\b(canada|india|united kingdom|\buk\b|germany|ireland|france|poland|"
    r"japan|australia|brazil|mexico|netherlands|spain|portugal|israel|"
    r"sweden|denmark|norway|finland|switzerland|austria|belgium|italy|"
    r"romania|czech|hungary|philippines|indonesia|malaysia|vietnam|china|"
    r"korea|taiwan|argentina|chile|colombia|peru|costa rica|nigeria|kenya|"
    r"south africa|egypt|\buae\b|dubai|new zealand|estonia|latvia|"
    r"lithuania|greece|croatia|serbia|turkey|ukraine|bulgaria|slovakia|"
    r"latin america|south america|\bemea\b|\bapac\b|\bnsw\b|\bnz\b|\bau\b|"
    r"auckland|wellington|brisbane|perth)\b",
    re.IGNORECASE)


def _keep_us(job: Dict[str, Any]) -> bool:
    hint = job.get("country_hint") or ""
    if hint:
        return hint in _COUNTRY_OK
    loc = job.get("location") or ""
    if not loc.strip():
        # Board rows with no location at all are usually remote-anywhere;
        # keep only if explicitly remote (US-ness can't be proven either way).
        return bool(job.get("is_remote"))
    if _FOREIGN_COUNTRY_RE.search(loc):
        return False
    if _US_WORD_RE.search(loc) or _US_STATE_RE.search(loc):
        return _geo_keep_us(loc)  # US signal present — normal tiering decides
    if _FOREIGN_CITY_RE.search(loc):
        return False
    # No country field — fall back to the Workday location-text tiering.
    return _geo_keep_us(loc)


# ----------------------------------------------------------------------
# Relevance keep-filter (boards return EVERYTHING; Workday searched for us)
# ----------------------------------------------------------------------

# Role nouns worth keeping even without a full term match — boards return
# their ENTIRE openings list (Workday searched for us), so recall depends on
# this net. "Backend Engineer" / "Site Reliability Engineer" / "Infrastructure
# Engineer" must survive a "devops engineer, software developer" term set.
_ROLE_NOUN_RE = re.compile(
    r"engineer|developer|scientist|architect|devops|\bsre\b|programmer",
    re.IGNORECASE)


def _keep_relevant(jobs: List[Dict[str, Any]], term_res: List[re.Pattern],
                   skill_res: List[re.Pattern]) -> List[Dict[str, Any]]:
    """Keep rows a Workday CXS search WOULD have retrieved, tiered:
      0 - a query term matches the title (best)
      1 - the title carries an engineering role noun, or the description
          mentions >=2 distinct resume skills (the differently-titled-but-
          matching-skills recall path)
    The tier drives the per-company cap so term matches never lose their
    slot to generic engineer rows."""
    out = []
    for j in jobs:
        title = j["title"].lower()
        hits = [rx.pattern for rx in term_res if rx.search(title)]
        if hits:
            j["matched_terms"] = hits[:3]
            j["_tier"] = 0
            out.append(j)
            continue
        if _ROLE_NOUN_RE.search(title):
            j["matched_terms"] = []
            j["_tier"] = 1
            out.append(j)
            continue
        desc = (j.get("description") or "").lower()
        if desc and sum(1 for rx in skill_res if rx.search(desc)) >= 2:
            j["matched_terms"] = []
            j["_tier"] = 1
            out.append(j)
    return out


# ----------------------------------------------------------------------
# Detail enrichment for rows that arrived without descriptions
# (greenhouse content, smartrecruiters ad, workable v2 job)
# ----------------------------------------------------------------------

def _detail_one(job: Dict[str, Any]) -> bool:
    ats, slug = job.get("ats"), job.get("tenant")
    rid = str(job["job_id"]).rsplit(":", 1)[-1]
    try:
        if ats == "greenhouse":
            r = _SESSION.get(
                f"https://boards-api.greenhouse.io/v1/boards/{slug}/jobs/{rid}",
                timeout=DETAIL_TIMEOUT)
            if r.status_code != 200:
                return False
            job["description"] = _html_to_text((r.json() or {}).get("content") or "")[:5000]
            return bool(job["description"])
        if ats == "smartrecruiters":
            r = _SESSION.get(
                f"https://api.smartrecruiters.com/v1/companies/{slug}/postings/{rid}",
                timeout=DETAIL_TIMEOUT)
            if r.status_code != 200:
                return False
            ad = ((r.json() or {}).get("jobAd") or {}).get("sections") or {}
            text = " ".join(
                _html_to_text((ad.get(k) or {}).get("text") or "")
                for k in ("jobDescription", "qualifications", "additionalInformation"))
            job["description"] = text.strip()[:5000]
            return bool(job["description"])
        if ats == "workable":
            r = _SESSION.get(
                f"https://apply.workable.com/api/v2/accounts/{slug}/jobs/{rid}",
                timeout=DETAIL_TIMEOUT)
            if r.status_code != 200:
                return False
            data = r.json() or {}
            job["description"] = _html_to_text(
                (data.get("description") or "") + " " +
                (data.get("requirements") or ""))[:5000]
            return bool(job["description"])
    except (requests.RequestException, ValueError):
        return False
    return False


def _enrich_details(jobs: List[Dict[str, Any]]) -> int:
    need = [j for j in jobs if not j.get("description")
            and j.get("ats") in ("greenhouse", "smartrecruiters", "workable")]
    if not need:
        return 0
    done = 0
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
        for ok in pool.map(_detail_one, need):
            done += 1 if ok else 0
    return done


# ----------------------------------------------------------------------
# Cache (same two-tier pattern as the Workday tab)
# ----------------------------------------------------------------------

def _get_cache_collection():
    try:
        from utils.db_connect import DBConnect
        db = DBConnect().get_db()
        coll = db[CACHE_COLLECTION]
        try:
            coll.create_index("cached_at", expireAfterSeconds=CACHE_TTL_SECONDS)
            coll.create_index("cache_key")
        except Exception:
            pass
        return coll
    except Exception as e:
        logger.warning("career-pages: cache unavailable: %s", e)
        return None


def _cache_key(rows: List[Dict[str, str]], terms: List[str], us_only: bool) -> str:
    basis = json.dumps({
        "v": RESULT_SCHEMA_VERSION,
        "slugs": sorted(f"{r['ats']}:{r['slug']}" for r in rows),
        "terms": sorted(t.lower() for t in terms),
        "us": bool(us_only),
    }, sort_keys=True)
    return hashlib.sha256(basis.encode()).hexdigest()


def _read_cache(coll, key: str) -> Optional[List[Dict[str, Any]]]:
    if coll is None:
        return None
    try:
        doc = coll.find_one({"cache_key": key})
        if not doc:
            return None
        age = (datetime.now(timezone.utc)
               - doc["cached_at"].replace(tzinfo=timezone.utc)).total_seconds()
        if age > CACHE_FRESH_SECONDS:
            return None
        return doc.get("jobs") or []
    except Exception:
        return None


def _write_cache(coll, key: str, jobs: List[Dict[str, Any]]) -> None:
    if coll is None:
        return
    try:
        coll.update_one(
            {"cache_key": key},
            {"$set": {"cache_key": key, "jobs": jobs,
                      "cached_at": datetime.now(timezone.utc)}},
            upsert=True)
    except Exception as e:
        logger.warning("career-pages: cache write failed: %s", e)


def _apply_career_sponsorship(jobs: List[Dict[str, Any]]) -> None:
    """Override company-tier sponsorship with the CAREER catalog's data.

    _attach_sponsorship looks tenants up in the WORKDAY tier table, which
    career slugs never (correctly) hit — everything lands "unknown". The
    career research (FY2024/25 USCIS data keyed by career slug) is
    authoritative here; JD-level refusals always stand.
    """
    try:
        from services.h1b_sponsor_data_careers import CAREER_H1B_SPONSORS
    except Exception:  # pragma: no cover
        return
    for job in jobs:
        if job.get("sponsorship") == "refused":
            continue
        info = CAREER_H1B_SPONSORS.get(job.get("tenant") or "")
        if not info:
            continue
        tier, approvals = info
        if tier in ("high", "medium"):
            job["sponsorship"] = "likely"
            job["h1b_sponsor"] = True
            job["sponsor_note"] = (
                f"{job['company']} ≈{approvals:,} H-1B approvals/yr (recent USCIS data)")
        elif tier == "low":
            job["sponsorship"] = "rare"
            job["sponsor_note"] = f"{job['company']} files few H-1Bs (≈{approvals}/yr)"


# ----------------------------------------------------------------------
# Entry point
# ----------------------------------------------------------------------

def run_career_pages_search(
    payload: Dict[str, Any],
    partial_cb: Optional[Callable[[Dict[str, Any]], None]] = None,
) -> Dict[str, Any]:
    """Execute one Career Pages search (async job runner entry).

    payload mirrors the Workday tab: titles, industries, companies (slugs),
    location (unused server-side beyond US filter), remote_only, us_only,
    force_refresh, user_email.
    """
    titles = [str(t).strip() for t in (payload.get("titles") or []) if str(t or "").strip()]
    industries = {str(i).strip() for i in (payload.get("industries") or []) if str(i or "").strip()}
    companies = {str(x).strip().lower() for x in (payload.get("companies") or []) if str(x or "").strip()}
    remote_only = bool(payload.get("remote_only", False))
    us_only = bool(payload.get("us_only", True))
    force_refresh = bool(payload.get("force_refresh", False))
    user_email = str(payload.get("user_email") or "")

    rows = [
        r for r in CAREER_PAGES_CATALOG
        if r["ats"] in FETCHERS
        and (not industries or r.get("industry") in industries)
        and (not companies or r["slug"].lower() in companies)
    ]
    skills, resume_years = _load_resume_profile(user_email)
    title_terms = _derive_query_terms(titles, cap=MAX_QUERY_TERMS)
    skill_terms = _derive_skill_terms(skills, title_terms,
                                      cap=TOTAL_TERMS_CAP - len(title_terms))
    terms = title_terms + skill_terms
    term_res = [re.compile(re.escape(t), re.IGNORECASE) for t in title_terms]
    # Broaden title matching: individual role tokens too ("devops engineer"
    # must keep "Senior DevOps & Platform Engineer").
    for t in title_terms:
        toks = [w for w in t.split() if len(w) > 3]
        if len(toks) >= 2:
            term_res.append(re.compile(
                r".*".join(re.escape(w) for w in toks), re.IGNORECASE))
    skill_res = [rx for rx in (_build_match_regex(s) for s in skills[:30]) if rx]

    errors: List[str] = []
    coll = _get_cache_collection()
    key = _cache_key(rows, terms, us_only)
    cache_hit = False
    raw_jobs: Optional[List[Dict[str, Any]]] = None
    if not force_refresh:
        raw_jobs = _read_cache(coll, key)
        cache_hit = raw_jobs is not None

    companies_total = len(rows)
    companies_done = 0
    companies_with_results = 0
    diagnostics = {"task_errors": 0}

    if raw_jobs is None:
        collected: List[Dict[str, Any]] = []
        done = 0
        hits: set = set()
        matchers = _role_matchers(titles)
        stream_rx = [(s, _build_match_regex(s)) for s in skills[:30]]
        prov_cache: Dict[str, Tuple[int, List[str]]] = {}

        def _provisional(j: Dict[str, Any]) -> Tuple[int, List[str]]:
            cached = prov_cache.get(j["job_id"])
            if cached is None:
                blob = (j["title"] + "\n" + (j.get("description") or "")[:1500]).lower()
                tl = j["title"].lower()
                tm = any(all(tok in tl for tok in m) for m in matchers)
                matched = [s for s, rx in stream_rx if rx is not None and rx.search(blob)]
                score = min(100, min(55, len(matched) * 6) + (45 if tm else (20 if matched else 0)))
                if not skills and not tm:
                    score = 15
                cached = (score, matched[:8])
                prov_cache[j["job_id"]] = cached
            return cached

        def _snapshot() -> None:
            if not partial_cb:
                return
            rows_snap = list({j["job_id"]: j for j in collected}.values())
            for j in rows_snap:
                sc, mt = _provisional(j)
                j["match_score"] = sc
                j["matched_skills"] = mt
                j.setdefault("missing_skills", [])
            rows_snap.sort(key=lambda x: (
                -x["match_score"],
                x.get("days_ago") if x.get("days_ago") is not None else 99))
            try:
                partial_cb({
                    "progress": {"tenants_done": done,
                                 "tenants_total": companies_total,
                                 "jobs_found": len(rows_snap)},
                    "jobs": [
                        {k: v for k, v in j.items() if k != "description"}
                        for j in rows_snap[:STREAM_TOP]
                    ],
                    "total": len(rows_snap),
                    "streaming": True,
                })
            except Exception:
                pass

        def _one_company(c: Dict[str, str]) -> Tuple[List[Dict[str, Any]], Optional[str]]:
            try:
                jobs_c = FETCHERS[c["ats"]](c)
            except Exception as e:
                return [], f"{c['slug']}: {type(e).__name__}"
            jobs_c = [j for j in jobs_c
                      if j.get("days_ago") is not None and j["days_ago"] <= WINDOW_DAYS]
            if us_only:
                jobs_c = [j for j in jobs_c if _keep_us(j)]
            jobs_c = _keep_relevant(jobs_c, term_res, skill_res)
            jobs_c.sort(key=lambda j: (j.get("_tier", 1), j.get("days_ago") or 0))
            jobs_c = jobs_c[:PER_COMPANY_KEEP]
            for j in jobs_c:
                j.pop("_tier", None)
            return jobs_c, None

        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
            futures = {pool.submit(_one_company, c): c for c in rows}
            try:
                for fut in as_completed(futures, timeout=OVERALL_TIMEOUT):
                    c = futures[fut]
                    done += 1
                    try:
                        items, err = fut.result()
                    except Exception as e:  # pragma: no cover
                        items, err = [], str(e)
                    if err:
                        diagnostics["task_errors"] += 1
                    if items:
                        hits.add(c["slug"])
                        collected.extend(items)
                    if partial_cb and done % STREAM_EVERY_TASKS == 0:
                        _snapshot()
            except TimeoutError:
                pending = sum(1 for f in futures if not f.done())
                errors.append(f"timeout: {pending} companies did not finish")
                for f in futures:
                    if not f.done():
                        f.cancel()
        companies_done = done
        companies_with_results = len(hits)
        raw_jobs = list({j["job_id"]: j for j in collected}.values())
        _write_cache(coll, key, raw_jobs)
    else:
        companies_done = companies_total
        companies_with_results = len({j.get("tenant") for j in raw_jobs})

    # Serve path: recompute recency, apply window + remote filters.
    jobs = []
    for j0 in raw_jobs:
        j = dict(j0)
        days = _days_ago(j.get("date_posted") or "")
        if days is None or days > WINDOW_DAYS:
            continue
        j["days_ago"] = days
        j["posted_text"] = _posted_text(days)
        jobs.append(j)
    if remote_only:
        jobs = [j for j in jobs if j.get("is_remote")]

    def _rank(items: List[Dict[str, Any]]) -> None:
        items.sort(key=lambda j: (
            -(j.get("match_score") or 0),
            j.get("days_ago") if j.get("days_ago") is not None else 99))

    jobs = _score_jobs(jobs, titles, skills, skill_terms)
    _rank(jobs)

    if partial_cb:
        try:
            partial_cb({
                "progress": {"tenants_done": companies_total,
                             "tenants_total": companies_total,
                             "jobs_found": len(jobs), "phase": "details"},
                "jobs": [{k: v for k, v in j.items() if k != "description"}
                         for j in jobs[:STREAM_TOP]],
                "total": len(jobs), "streaming": True,
            })
        except Exception:
            pass

    top = jobs[:DETAIL_ENRICH_TOP] + [
        j for j in jobs[DETAIL_ENRICH_TOP:]
        if (j.get("days_ago") if j.get("days_ago") is not None else 99) <= 3
    ][:DETAIL_ENRICH_RECENT]
    if _enrich_details(top):
        _score_jobs(top, titles, skills, skill_terms)
        _rank(jobs)
        if coll is not None:
            by_id = {j["job_id"]: j for j in top if j.get("description")}
            for rj in raw_jobs:
                e = by_id.get(rj["job_id"])
                if e is not None:
                    rj["description"] = e["description"]
            _write_cache(coll, key, raw_jobs)

    jobs = jobs[:GLOBAL_KEEP]
    _attach_feasibility(jobs, skills, resume_years)
    _rank(jobs)
    _attach_sponsorship(jobs)
    _apply_career_sponsorship(jobs)
    _drain_pools()

    window_counts = {"today": 0, "d1": 0, "d3": 0, "d7": 0, "d30": 0}
    for j in jobs:
        d = j.get("days_ago")
        if d is None:
            continue
        if d == 0:
            window_counts["today"] += 1
        if d <= 1:
            window_counts["d1"] += 1
        if d <= 3:
            window_counts["d3"] += 1
        if d <= 7:
            window_counts["d7"] += 1
        if d <= 30:
            window_counts["d30"] += 1

    return {
        "ok": True,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "jobs": jobs,
        "total": len(jobs),
        "window_counts": window_counts,
        "query_terms": terms,
        "tenants_total": companies_total,
        "tenants_done": companies_done,
        "tenants_with_results": companies_with_results,
        "industries_available": INDUSTRIES,
        "ats_available": ATS_KINDS,
        "cache_hit": cache_hit,
        "us_only": us_only,
        "resume_skill_count": len(skills),
        "diagnostics": diagnostics,
        "errors": errors[:20],
    }


def catalog_summary() -> Dict[str, Any]:
    by_ind: Dict[str, List[Dict[str, str]]] = {}
    for r in CAREER_PAGES_CATALOG:
        by_ind.setdefault(r["industry"], []).append(r)
    return {
        "total": len(CAREER_PAGES_CATALOG),
        "industries": [
            {"key": k, "count": len(v),
             "companies": [{"name": r["display_name"], "tenant": r["slug"],
                            "ats": r["ats"]} for r in
                           sorted(v, key=lambda x: x["display_name"].lower())]}
            for k, v in sorted(by_ind.items())
        ],
    }
